# Generated by Django 4.1.6 on 2023-02-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(default=None, upload_to='posters'),
            preserve_default=False,
        ),
    ]
