# Generated by Django 4.1.7 on 2023-03-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_film_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.AddField(
            model_name='film',
            name='premier_russia',
            field=models.DateField(default=None, verbose_name='Премьера в России'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='premier_word',
            field=models.DateField(default=None, verbose_name='Премьера в мире'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='film',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='film',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='posters', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(to='films.genre'),
        ),
    ]
